"""Tournament team name → Sports Reference CBB URL slug mapping.

Keys are the canonical team names used in bracket JSON imports.
Values are the Sports Reference school slugs used in URLs like:
  https://www.sports-reference.com/cbb/schools/{slug}/2025.html

Usage:
    from bracket_team.scraper.team_slug_map import TEAM_SLUG_MAP
    slug = TEAM_SLUG_MAP.get("UConn")  # → "connecticut"
"""

TEAM_SLUG_MAP: dict[str, str] = {
    # East Region seeds 1-16
    "Auburn": "auburn",
    "Louisville": "louisville",
    "Creighton": "creighton",
    "Michigan": "michigan",
    "Michigan State": "michigan-state",
    "Texas": "texas",
    "Iowa": "iowa",
    "Maryland": "maryland",
    "West Virginia": "west-virginia",
    "Boise State": "boise-state",
    "North Carolina": "north-carolina",
    "New Mexico": "new-mexico",
    "Yale": "yale",
    "Lipscomb": "lipscomb",
    "Bryant": "bryant",
    "Alabama State": "alabama-state",
    # West Region seeds 1-16
    "Duke": "duke",
    "Alabama": "alabama",
    "Wisconsin": "wisconsin",
    "Arizona": "arizona",
    "Oregon": "oregon",
    "BYU": "brigham-young",
    "Saint Mary's": "saint-marys-ca",
    "Mississippi State": "mississippi-state",
    "Baylor": "baylor",
    "Vanderbilt": "vanderbilt",
    "Drake": "drake",
    "Liberty": "liberty",
    "Akron": "akron",
    "Montana": "montana",
    "Robert Morris": "robert-morris",
    "SFA": "stephen-f-austin",
    # South Region seeds 1-16
    "Houston": "houston",
    "Tennessee": "tennessee",
    "Kentucky": "kentucky",
    "Purdue": "purdue",
    "Clemson": "clemson",
    "Illinois": "illinois",
    "UCLA": "ucla",
    "Gonzaga": "gonzaga",
    "Georgia": "georgia",
    "Utah State": "utah-state",
    "Texas A&M": "texas-am",
    "McNeese State": "mcneese-state",
    "High Point": "high-point",
    "Troy": "troy",
    "Wofford": "wofford",
    "SIUE": "siue",
    # Midwest Region seeds 1-16
    "Florida": "florida",
    "St. John's": "st-johns-ny",
    "St Johns NY": "st-johns-ny",
    "Texas Tech": "texas-tech",
    "Maryland Terrapins": "maryland",
    "Memphis": "memphis",
    "Missouri": "missouri",
    "Kansas": "kansas",
    "Connecticut": "connecticut",
    "UConn": "connecticut",
    "Oklahoma": "oklahoma",
    "Arkansas": "arkansas",
    "Colorado State": "colorado-state",
    "Grand Canyon": "grand-canyon",
    "UNC Wilmington": "unc-wilmington",
    "Omaha": "nebraska-omaha",
    "Norfolk State": "norfolk-state",
    # Additional common tournament teams
    "Villanova": "villanova",
    "Syracuse": "syracuse",
    "Georgetown": "georgetown",
    "Providence": "providence",
    "Seton Hall": "seton-hall",
    "Xavier": "xavier",
    "Marquette": "marquette",
    "Butler": "butler",
    "DePaul": "depaul",
    "Indiana": "indiana",
    "Ohio State": "ohio-state",
    "Penn State": "penn-state",
    "Michigan Wolverines": "michigan",
    "Nebraska": "nebraska",
    "Northwestern": "northwestern",
    "Minnesota": "minnesota",
    "Iowa State": "iowa-state",
    "Kansas State": "kansas-state",
    "Oklahoma State": "oklahoma-state",
    "TCU": "texas-christian",
    "West Virginia Mountaineers": "west-virginia",
    "Cincinnati": "cincinnati",
    "UCF": "central-florida",
    "Central Florida": "central-florida",
    "South Florida": "south-florida",
    "Wichita State": "wichita-state",
    "Temple": "temple",
    "SMU": "southern-methodist",
    "East Carolina": "east-carolina",
    "Tulsa": "tulsa",
    "North Carolina State": "north-carolina-state",
    "NC State": "north-carolina-state",
    "Virginia": "virginia",
    "Virginia Tech": "virginia-tech",
    "Wake Forest": "wake-forest",
    "Notre Dame": "notre-dame",
    "Pittsburgh": "pittsburgh",
    "Miami FL": "miami-fl",
    "Miami": "miami-fl",
    "Florida State": "florida-state",
    "Georgia Tech": "georgia-tech",
    "Boston College": "boston-college",
    "Stanford": "stanford",
    "Cal": "california",
    "California": "california",
    "USC": "southern-california",
    "Washington": "washington",
    "Washington State": "washington-state",
    "Colorado": "colorado",
    "Utah": "utah",
    "Arizona State": "arizona-state",
    "LSU": "lsu",
    "Mississippi": "mississippi",
    "Ole Miss": "mississippi",
    "South Carolina": "south-carolina",
    "Vanderbilt Commodores": "vanderbilt",
    "Missouri Tigers": "missouri",
    "San Diego State": "san-diego-state",
    "UNLV": "unlv",
    "Nevada": "nevada",
    "Fresno State": "fresno-state",
    "Air Force": "air-force",
    "Wyoming": "wyoming",
    "San Jose State": "san-jose-state",
    "Hawaii": "hawaii",
    "New Mexico State": "new-mexico-state",
    "Memphis Tigers": "memphis",
    "FAU": "florida-atlantic",
    "Florida Atlantic": "florida-atlantic",
    "UAB": "uab",
    "Charlotte": "charlotte",
    "Middle Tennessee": "middle-tennessee",
    "Marshall": "marshall",
    "Western Kentucky": "western-kentucky",
    "Southern Miss": "southern-mississippi",
    "UTSA": "utsa",
    "VCU": "virginia-commonwealth",
    "Virginia Commonwealth": "virginia-commonwealth",
    "Richmond": "richmond",
    "George Mason": "george-mason",
    "Davidson": "davidson",
    "Dayton": "dayton",
    "Rhode Island": "rhode-island",
    "Saint Louis": "saint-louis",
    "La Salle": "la-salle",
    "George Washington": "george-washington",
    "UMass": "massachusetts",
    "Massachusetts": "massachusetts",
    "Fordham": "fordham",
    "Penn": "pennsylvania",
    "Princeton": "princeton",
    "Harvard": "harvard",
    "Columbia": "columbia",
    "Cornell": "cornell",
    "Brown": "brown",
    "Dartmouth": "dartmouth",
    "Murray State": "murray-state",
    "Belmont": "belmont",
    "Jacksonville State": "jacksonville-state",
    "Eastern Washington": "eastern-washington",
    "Oral Roberts": "oral-roberts",
    "Abilene Christian": "abilene-christian",
    "North Texas": "north-texas",
    "UTEP": "utep",
    "Louisiana Tech": "louisiana-tech",
    "Sam Houston State": "sam-houston-state",
    "Stephen F. Austin": "stephen-f-austin",
    "Nicholls State": "nicholls-state",
    "Southeastern Louisiana": "southeastern-louisiana",
    "Colgate": "colgate",
    "Bucknell": "bucknell",
    "Loyola MD": "loyola-md",
    "American": "american",
    "Holy Cross": "holy-cross",
    "Lehigh": "lehigh",
    "Army": "army",
    "Navy": "navy",
    "Patriot": "patriot",
    # Mid-majors / frequent tournament teams
    "Longwood": "longwood",
    "College of Charleston": "charleston",
    "Col. of Charleston": "charleston",
    "Wagner": "wagner",
    "Grambling": "grambling",
    "Grambling State": "grambling",
    "Montana State": "montana-state",
    "Vermont": "vermont",
    "UCSB": "uc-santa-barbara",
    "UC Santa Barbara": "uc-santa-barbara",
    "UC Irvine": "uc-irvine",
    "UC Davis": "uc-davis",
    "UC Riverside": "uc-riverside",
    "Long Beach State": "long-beach-state",
    "Cal State Fullerton": "cal-state-fullerton",
    "Cal State Northridge": "cal-state-northridge",
    "Hawaii Rainbow Warriors": "hawaii",
    "Portland State": "portland-state",
    "Idaho State": "idaho-state",
    "Northern Iowa": "northern-iowa",
    "South Dakota State": "south-dakota-state",
    "North Dakota State": "north-dakota-state",
    "Weber State": "weber-state",
    "Southern Utah": "southern-utah",
    "Idaho": "idaho",
    "Eastern Illinois": "eastern-illinois",
    "Northern Illinois": "northern-illinois",
    "Western Illinois": "western-illinois",
    "Illinois State": "illinois-state",
    "Indiana State": "indiana-state",
    "Missouri State": "missouri-state",
    "Southern Illinois": "southern-illinois",
    "Bradley": "bradley",
    "Evansville": "evansville",
    "Loyola Chicago": "loyola-il",
    "Detroit Mercy": "detroit-mercy",
    "Wright State": "wright-state",
    "Green Bay": "wisconsin-green-bay",
    "Milwaukee": "wisconsin-milwaukee",
    "Oakland": "oakland",
    "IUPUI": "iupui",
    "Youngstown State": "youngstown-state",
    "Cleveland State": "cleveland-state",
    "Northern Kentucky": "northern-kentucky",
    "Purdue Fort Wayne": "purdue-fort-wayne",
    "Saint Francis PA": "saint-francis-pa",
    "Sacred Heart": "sacred-heart",
    "Central Connecticut": "central-connecticut",
    "Fairleigh Dickinson": "fairleigh-dickinson",
    "LIU": "long-island-university",
    "Long Island": "long-island-university",
    "Mount St. Mary's": "mount-st-marys",
    "St. Francis NY": "st-francis-ny",
    "Stony Brook": "stony-brook",
    "NJIT": "njit",
    "Hartford": "hartford",
    "Maine": "maine",
    "New Hampshire": "new-hampshire",
    "Albany": "albany-ny",
    "Binghamton": "binghamton",
    "UMass Lowell": "massachusetts-lowell",
    "North Carolina A&T": "north-carolina-at",
    "North Carolina Central": "north-carolina-central",
    "Howard": "howard",
    "Morgan State": "morgan-state",
    "Coppin State": "coppin-state",
    "Maryland Eastern Shore": "maryland-eastern-shore",
    "Delaware State": "delaware-state",
    "UMES": "maryland-eastern-shore",
    "Hampton": "hampton",
    "South Carolina State": "south-carolina-state",
    "Bethune-Cookman": "bethune-cookman",
    "Florida A&M": "florida-am",
    "Prairie View A&M": "prairie-view",
    "PV A&M": "prairie-view",
    "Texas Southern": "texas-southern",
    "Jackson State": "jackson-state",
    "Alcorn State": "alcorn-state",
    "Southern": "southern",
    "McNeese": "mcneese-state",
    "Incarnate Word": "incarnate-word",
    "Tarleton State": "tarleton-state",
    "Houston Baptist": "houston-christian",
    "Houston Christian": "houston-christian",
    "Campbell": "campbell",
    "Winthrop": "winthrop",
    "Gardner-Webb": "gardner-webb",
    "Presbyterian": "presbyterian",
    "Charleston Southern": "charleston-southern",
    "UNC Asheville": "unc-asheville",
    "UNC Greensboro": "unc-greensboro",
    "Western Carolina": "western-carolina",
    "Samford": "samford",
    "Furman": "furman",
    "The Citadel": "the-citadel",
    "VMI": "virginia-military-institute",
    "Mercer": "mercer",
    "East Tennessee State": "east-tennessee-state",
    "ETSU": "east-tennessee-state",
    "Chattanooga": "chattanooga",
    "UT Martin": "tennessee-martin",
    "Tennessee Tech": "tennessee-tech",
    "Bellarmine": "bellarmine",
    "Eastern Kentucky": "eastern-kentucky",
    "Morehead State": "morehead-state",
    "Austin Peay": "austin-peay",
    "Southeast Missouri State": "southeast-missouri-state",
    "Tennessee State": "tennessee-state",
    "Jacksonville": "jacksonville",
    "Kennesaw State": "kennesaw-state",
    "Cal Baptist": "california-baptist",
    "Santa Clara": "santa-clara",
    "North Florida": "north-florida",
    "Florida Gulf Coast": "florida-gulf-coast",
    "FGCU": "florida-gulf-coast",
    "Stetson": "stetson",
    "North Alabama": "north-alabama",
    "USC Upstate": "usc-upstate",
    "Queens": "queens-nc",
    "Radford": "radford",
    "Coastal Carolina": "coastal-carolina",
    "Appalachian State": "appalachian-state",
    "James Madison": "james-madison",
    "Towson": "towson",
    "William & Mary": "william-mary",
    "Drexel": "drexel",
    "Hofstra": "hofstra",
    "Delaware": "delaware",
    "Northeastern": "northeastern",
    "Elon": "elon",
    "UNCW": "unc-wilmington",
    "Quinnipiac": "quinnipiac",
    "Manhattan": "manhattan",
    "Siena": "siena",
    "Marist": "marist",
    "Canisius": "canisius",
    "Niagara": "niagara",
    "Fairfield": "fairfield",
    "Rider": "rider",
    "Monmouth": "monmouth",
    "Saint Peter's": "saint-peters",
    "UMBC": "umbc",
    "Loyola Baltimore": "loyola-md",
    "Lafayette": "lafayette",
    "Boston University": "boston-university",
    "American University": "american",
    "AU": "american",
}
